permalink: :pretty
title: YEGRB
subtitle: "Edmonton's Rubyists Rejoice"
author_name: YEGRB
webmaster_email: mark@yegrb.com
homepage_url: http://yegrb.com
atom_url: /atom.xml
rss_url: /rss.xml
paginate: 5
exclude: [ 'README', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'build', 'bin' ]
